resolver: lts-22.41

packages:
- .

extra-deps:
  - opaleye-0.9.2.0 
  - product-profunctors-0.11.0.3 
  - uuid-1.3.15
  - net-mqtt-0.8.6.2
  - unix-2.8.4.0
  - sqlite-simple-0.4.19.0
  
allow-newer: true
