GET http://localhost:3000/api/wanaka/sensor/zone/e18e45fe-28bd-4a75-a6a8-c51cd4d23a25 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjQxNTc3ODIsInVzZXIiOiIyOTcyMmMxZi0xOTIwLTQzMjctOTM2OC02MjY3OTBjYTY0YjYifQ.6mwua1P1RHWojRyF0l-6tutKAYHyViQKEYokp-RUNFU
