GET http://localhost:3000/api/wanaka/activity HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTE5OTYwMjQsInVzZXIiOiIzYmQyMzlkNC0wM2QxLTQ3Y2UtYWUyMC1kYjE1YjIzOTgwMTEifQ.dWnbfH2PfpcEtN5yK3-pRh9TQu7bO7hhGCoMvpE2C1s