GET http://localhost:3000/api/wanaka/profile/3bd239d4-03d1-47ce-ae20-db15b2398011 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NTEzOTUwMDUsInVzZXIiOiJhcGktZGV2In0.KX5KYIb0YqxEa-i2sKUXgyQGC--CQCqzDMYM3Oq2gb0